//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBankVoorBoeken
{
    using System;
    using System.Collections.Generic;
    
    public partial class Boeken
    {
        public int id { get; set; }
        public string Title { get; set; }
        public int AantalPaginas { get; set; }
        public int Score { get; set; }
        public Nullable<int> Publicatie { get; set; }
        public int uitgeverld { get; set; }
    }
}
